In [1]:
#importo le libreirie necessarie per analizzare i dati
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
#importo i dati dal csv e creo il mio data_set locale
players_df= pd.read_csv('players.csv')
players_df=players_df[['player_id','name','last_season','country_of_citizenship','date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'market_value_in_eur', 'highest_market_value_in_eur','agent_name', 'current_club_name']]
players_df=players_df.drop_duplicates()
players_df=players_df.dropna()
players_df

,player_id,name,last_season,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,agent_name,current_club_name
89,22860,Jesper Hansen,2023,Denmark,1985-03-31,Goalkeeper,Goalkeeper,right,188.0,200000.0,1000000.0,Boutique Transfers,Aarhus GF
93,23365,Reginaldo,2012,Brazil,1983-07-31,Centre-Forward,Attack,right,175.0,10000.0,3500000.0,Soccer 3,Siena FC
107,27941,Danijel Subasic,2019,Croatia,1984-10-27,Goalkeeper,Goalkeeper,right,191.0,50000.0,6000000.0,TTMA,AS Monaco
116,29962,Daniele Dessena,2019,Italy,1987-05-10,Central Midfield,Midfield,right,182.0,200000.0,4000000.0,BC Group,Brescia Calcio
118,30321,Óscar Trejo,2023,Argentina,1988-04-26,Attacking Midfield,Midfield,right,180.0,2500000.0,4000000.0,Eleven Talent Group,Rayo Vallecano
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30293,99523,Nícolas,2020,Brazil,1988-04-12,Goalkeeper,Goalkeeper,right,190.0,300000.0,900000.0,Grimaldi Mariano,Udinese Calcio
30295,288499,Ewandro Costa,2017,Brazil,1996-03-15,Centre-Forward,Attack,left,176.0,450000.0,1000000.0,Trust Football,Udinese Calcio
30297,371851,Jaka Bijol,2023,Slovenia,1999-02-05,Centre-Back,Defender,right,190.0,10000000.0,10000000.0,MSC GROUP,Udinese Calcio
30299,586756,Festy Ebosele,2023,Ireland,2002-08-02,Right Midfield,Midfield,right,180.0,4500000.0,4500000.0,The Kulture Group,Udinese Calcio
30301,925584,Axel Guessand,2023,France,2004-11-06,Centre-Back,Defender,left,184.0,250000.0,300000.0,CAA Stellar,Udinese Calcio

In [2]:
players_df.to_csv('Players_Nona.csv', index=False)

In [6]:
competitions_df= pd.read_csv('competitions.csv')
competitions_df=competitions_df[['competition_id', 'name', 'type', 'country_name', 'domestic_league_code']]
competitions_df=competitions_df.drop_duplicates()
competitions_df=competitions_df.dropna()
competitions_df

,competition_id,name,type,country_name,domestic_league_code
0,CIT,italy-cup,domestic_cup,Italy,IT1
1,NLSC,johan-cruijff-schaal,other,Netherlands,NL1
2,GRP,kypello-elladas,domestic_cup,Greece,GR1
3,POSU,supertaca-candido-de-oliveira,other,Portugal,PO1
4,RUSS,russian-super-cup,other,Russia,RU1
5,SUC,supercopa,other,Spain,ES1
7,DK1,superligaen,domestic_league,Denmark,DK1
9,ES1,laliga,domestic_league,Spain,ES1
10,FR1,ligue-1,domestic_league,France,FR1
11,IT1,serie-a,domestic_league,Italy,IT1
12,NL1,eredivisie,domestic_league,Netherlands,NL1
13,RUP,russian-cup,domestic_cup,Russia,RU1
14,PO1,liga-portugal-bwin,domestic_league,Portugal,PO1
15,BESC,belgian-supercup,other,Belgium,BE1
16,GB1,premier-league,domestic_league,England,GB1
18,CGB,efl-cup,other,England,GB1
19,DKP,sydbank-pokalen,domestic_cup,Denmark,DK1
21,FAC,fa-cup,domestic_cup,England,GB1
22,NLP,toto-knvb-beker,domestic_cup,Netherlands,NL1
23,UKRS,ukrainian-super-cup,other,Ukraine,UKR1
24,UKR1,premier-liga,domestic_league,Ukraine,UKR1
25,CDR,copa-del-rey,domestic_cup,Spain,ES1
27,GR1,super-league-1,domestic_league,Greece,GR1
28,TR1,super-lig,domestic_league,Turkey,TR1
29,POCP,allianz-cup,domestic_cup,Portugal,PO1
30,GBCS,community-shield,other,England,GB1
32,L1,bundesliga,domestic_league,Germany,L1
33,RU1,premier-liga,domestic_league,Russia,RU1
34,SC1,scottish-premiership,domestic_league,Scotland,SC1
35,SCI,supercoppa-italiana,other,Italy,IT1
36,BE1,jupiler-pro-league,domestic_league,Belgium,BE1
38,DFL,dfl-supercup,other,Germany,L1
39,SFA,sfa-cup,domestic_cup,Scotland,SC1
40,UKRP,ukrainian-cup,domestic_cup,Ukraine,UKR1
41,DFB,dfb-pokal,domestic_cup,Germany,L1
42,FRCH,trophee-des-champions,other,France,FR1

In [7]:
competitions_df.to_csv('competitions_Nona.csv', index=False)

In [2]:
club_df= pd.read_csv('clubs.csv')
club_df=club_df[['club_id','name','domestic_competition_id','squad_size','average_age','foreigners_number','foreigners_percentage', 'national_team_players','stadium_name','net_transfer_record']]
club_df=club_df.drop_duplicates()
club_df=club_df.dropna()
club_df = club_df[club_df['net_transfer_record'] != '+-0']
club_df

,club_id,name,domestic_competition_id,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,net_transfer_record
0,105,Sportverein Darmstadt 1898 e. V.,L1,30,26.4,11,36.7,1,Merck-Stadion am Böllenfalltor,€-1.60m
1,11127,FK Ural Yekaterinburg,RU1,25,28.2,13,52.0,5,Yekaterinburg Arena,€-770k
2,114,Beşiktaş Jimnastik Kulübü,TR1,32,27.4,16,50.0,13,Tüpraş Stadyumu,€-14.50m
3,12,Associazione Sportiva Roma,IT1,26,27.4,17,65.4,17,Olimpico di Roma,+€65.20m
4,148,Tottenham Hotspur Football Club,GB1,29,26.2,21,72.4,22,Tottenham Hotspur Stadium,€-130.40m
...,...,...,...,...,...,...,...,...,...,...
420,607,Venezia FC,IT1,27,25.6,17,63.0,5,Pier Luigi Penzo,+€4.83m
422,724,Football Club Volendam,NL1,29,22.8,14,48.3,3,Kras Stadion,+€1.80m
423,800,Atalanta Bergamasca Calcio S.p.a.,IT1,25,27.2,17,68.0,15,Gewiss Stadium,+€87.00m
424,979,Moreirense Futebol Clube,PO1,26,26.0,17,65.4,2,Estádio C. J. de Almeida Freitas,€-2.05m
425,984,West Bromwich Albion,GB1,25,27.8,8,32.0,4,The Hawthorns,€-1.35m

In [3]:
club_df.to_csv('clubs_Nona.csv', index=False)

In [9]:
#importo i dati dal csv e creo il mio data_set locale
appearances_df= pd.read_csv('appearances.csv')
appearances_df=appearances_df.drop_duplicates()
appearances_df.dropna(subset=['appearance_id'])
appearances_df

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2222589_118074,2222589,118074,2439,206,2012-07-22,Marcos Ureña,RU1,0,0,0,0,3
996,2222589_15018,2222589,15018,2700,498,2012-07-22,João Carlos,RU1,0,0,0,0,90
997,2222589_15597,2222589,15597,2439,2439,2012-07-22,Artur Tlisov,RU1,0,0,0,0,90
998,2222589_15743,2222589,15743,2439,41201,2012-07-22,Vladislav Kulik,RU1,0,0,0,0,71
999,2222589_15796,2222589,15796,2439,968,2012-07-22,Igor Lolo,RU1,1,0,0,1,90

In [10]:
appearances_df.to_csv('appearances_Nona.csv', index=False)

In [6]:
# Trova le righe dove appearances_id è null
null_appearances = appearances_df[appearances_df['appearance_id'].isnull()]

# Visualizza le righe con appearances_id null
null_appearances

Empty DataFrame
Columns: [appearance_id, game_id, player_id, player_club_id, player_current_club_id, date, player_name, competition_id, yellow_cards, red_cards, goals, assists, minutes_played]
Index: []

In [7]:
null_appearances = appearances_df[appearances_df['appearance_id'].isnull()]

# Righe con appearances_id duplicato (escludendo i null)
duplicate_appearances = appearances_df[appearances_df['appearance_id'].notnull() & appearances_df.duplicated('appearance_id', keep=False)]

# Combina entrambe le condizioni
problematic_appearances = pd.concat([null_appearances, duplicate_appearances])

# Visualizza le righe problematiche
problematic_appearances

Empty DataFrame
Columns: [appearance_id, game_id, player_id, player_club_id, player_current_club_id, date, player_name, competition_id, yellow_cards, red_cards, goals, assists, minutes_played]
Index: []

In [8]:
# Trova i duplicati in appearances_id (escludendo i null)
duplicate_appearances = appearances_df[appearances_df['appearance_id'].notnull() & appearances_df.duplicated('appearance_id', keep=False)]

# Visualizza le righe con appearances_id duplicato
duplicate_appearances

Empty DataFrame
Columns: [appearance_id, game_id, player_id, player_club_id, player_current_club_id, date, player_name, competition_id, yellow_cards, red_cards, goals, assists, minutes_played]
Index: []